version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - echo "install"
  pre_build:
    commands:
      - echo "pre_build"
  build:
    commands:
      - echo "build"
  post_build:
    commands:
      - echo "pos_build"