version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
  pre_build:  
    on-failure: ABORT
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY
  build:
    on-failure: ABORT
    commands:
      - echo "Docker build started"
      - docker build -t $IMAGE .
      - docker tag $IMAGE:$IMAGETAG $REPOSITORY/$IMAGE:$IMAGETAG
  post_build:
    on-failure: ABORT
    commands:
      - docker images ls -a
      - docker push $REPOSITORY/$IMAGE:$IMAGETAG